export * from "./authors";
export * from "./books";
export * from "./editorials";
export * from "./genders";
export * from "./favorites";
export * from "./loans";
export * from "./penalties";
export * from "./sanctions";
export * from "./notifications";
